### ISSUE TITLE
Posts programados

### ISSUE THREAD

**Issue by brunocalmels** [MacherIT/buho#8]
Los posts se deben poder programar para que se posteen en algún momento en el futuro.

Se puede hacer una tarea que cada cierto intervalo de tiempo (15 minutos?) corra una tarea (_rake task_ de Rails) que chequee si hay posts que deberían estar posteados y aún no se postearon, postearlos, y poner sus atributos _publicados_ al valor correspondiente.

Guía muy fácil de cómo crear Rails tasks en Heroku: https://devcenter.heroku.com/articles/scheduler

**Comment by GeroBlacksmith** [comment]
Al final con la Gem Koala encontramos la forma de agregar post utilizando el servicio interno de Facebook para programar los post, con imagen y todo
`res = @page_graph.put_picture(@post.imagen, {message:@post.texto,published:false,scheduled_publish_time: @post.hora_pub.to_time.to_i})`

**Comment by brunocalmels** [comment]
Perfect.
